
language: node_js

node_js:
  - 8
  - 10

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g coveralls

script:
  - npm run lint
  - npm run test

after_script:
  - cat ./coverage/lcov.info | coveralls

sudo: false
