
language: node_js

node_js:
  - 8
  - 10

cache:
  directories:
    - node_modules

before_script:
  - npm install -g coveralls
  - set +e

script:
  - npm run lint
  - npm run test
  - npm run build

deploy:
  provider: npm
  email: ricardo.ferro@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    node: 8

after_script:
  - cat ./coverage/lcov.info | coveralls

sudo: false
