
language: node_js

node_js:
  - 8
  - 10

cache:
  directories:
    - node_modules

before_script:
  - npm install -g coveralls

script:
  - npm run lint
  - npm run test

after_success:
  - cat ./coverage/lcov.info | coveralls

before_deploy:
  - npm run build

deploy:
  provider: npm
  email: ricardo.ferro@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
    node: 8

sudo: false
